version: '3'
services:
  database:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: delivery-app
  backend:
    build: ./back-end
    environment:
      - NODE_ENV=production
      - API_PORT=3002
      - MYSQL_HOST=database
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpw
      - MYSQL_DB_NAME=delivery-app
    ports:
      - "3001:3001"
    depends_on:
      - database
  frontend:
    build: ./front-end
    depends_on:
      - backend
    ports:
      - "8080:80"