version: '3'

services:
  database:
    container_name: mysql_db
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: delivery-app

  backend:
    container_name: backend
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MYSQL_HOST=database
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpw
      - MYSQL_DB_NAME=delivery-app
    build: ./back-end
    ports:
      - "3001:3001"
    depends_on:
      - database
    restart: always

  frontend:
    container_name: frontend
    build: ./front-end
    depends_on:
      - backend
      - database
    ports:
      - "8080:80"